from __future__ import annotations

TRANSLATIONS = {
    "en": {
        "new_chat": "New chat",
        "search": "Search conversations...",
        "history": "Chat history",
        "settings": "Settings",
        "greeting_title": "Hello!",
        "greeting_text": "What would you like to ask today?",
        "input_placeholder": "Enter your message...",
        "attach": "Attach",
        "camera": "Open camera",
        "choose_image": "Choose image",
        "general": "General",
        "settings_intro": "Adjust the app appearance and display language.",
        "appearance": "Appearance",
        "appearance_desc": "Choose the display theme for the app.",
        "language": "Language",
        "language_desc": "Choose the display language for the app.",
        "system": "System",
        "dark": "Dark",
        "light": "Light",
        "capture": "Capture",
        "camera_ready": "Camera is ready. Press Capture to add it to the chat.",
        "camera_unavailable": "Unable to open the camera.",
        "camera_missing": "opencv-python is not installed.",
        "camera_save_dir": "Saved photos folder: {path}",
        "camera_save_failed": "Could not save the captured photo.",
        "system_reply_text": "I received the content and will process it locally in this chat context.",
        "system_reply_image": "Image received. Local analysis will use it in this chat.",
        "image_model_error": "AI chat is unavailable in this build.",
        "system_unavailable": "AI chat has been removed from this build.",
        "system_reply_camera": "Camera snapshot received and added to the chat.",
        "empty_send": "Enter a message before sending.",
        "info_title": "Info",
        "loading_model": "Starting local voice processing...",
        "recording_status": "Listening...",
        "voice_error": "Could not recognize voice or Mic error.",
        "settings_title": "Settings",
        "camera_window": "Camera",
        "attach_image_label": "Selected image",
        "attach_text_label": "Text file",
        "attach_camera_label": "Camera snapshot",
        "mode_badge": "Mode",
        "today": "Today",
        "yesterday": "Yesterday",
        "days_ago": "days ago",
        "english": "English",
        "vietnamese": "Vietnamese",
        "delete_chat": "Delete chat",
        "confirm_delete_title": "Confirm Delete",
        "confirm_delete_msg": "Are you sure you want to delete this conversation?",
        "sidebar_expand": "Expand sidebar",
        "sidebar_collapse": "Collapse sidebar",
        "medical_analyzing": "Analyzing medical image...",
        "medical_pending": "Medical analysis is running...",
        "copied_hint": "Copied to clipboard!",
        "new_message": "New AI message",
    },
    "vi": {
        "copied_hint": "\u0110\u00e3 sao ch\u00e9p v\u00e0o b\u1ed9 nh\u1edb t\u1ea1m!",
        "new_message": "Tin nh\u1eafn m\u1edbi t\u1eeb AI",
        "new_chat": "Cu\u1ed9c tr\u00f2 chuy\u1ec7n m\u1edbi",
        "search": "T\u00ecm ki\u1ebfm cu\u1ed9c tr\u00f2 chuy\u1ec7n...",
        "history": "L\u1ecbch s\u1eed tr\u00f2 chuy\u1ec7n",
        "settings": "C\u00e0i \u0111\u1eb7t",
        "greeting_title": "Xin ch\u00e0o!",
        "greeting_text": "H\u00f4m nay b\u1ea1n mu\u1ed1n h\u1ecfi \u0111i\u1ec1u g\u00ec?",
        "input_placeholder": "Nh\u1eadp tin nh\u1eafn c\u1ee7a b\u1ea1n...",
        "attach": "\u0110\u00ednh k\u00e8m",
        "camera": "M\u1edf camera",
        "choose_image": "Ch\u1ecdn \u1ea3nh",
        "general": "Chung",
        "settings_intro": "\u0110i\u1ec1u ch\u1ec9nh giao di\u1ec7n v\u00e0 ng\u00f4n ng\u1eef hi\u1ec3n th\u1ecb c\u1ee7a \u1ee9ng d\u1ee5ng.",
        "appearance": "Giao di\u1ec7n",
        "appearance_desc": "Ch\u1ecdn giao di\u1ec7n hi\u1ec3n th\u1ecb cho \u1ee9ng d\u1ee5ng.",
        "language": "Ng\u00f4n ng\u1eef",
        "language_desc": "Ch\u1ecdn ng\u00f4n ng\u1eef hi\u1ec3n th\u1ecb cho \u1ee9ng d\u1ee5ng.",
        "system": "H\u1ec7 th\u1ed1ng",
        "dark": "T\u1ed1i",
        "light": "S\u00e1ng",
        "capture": "Ch\u1ee5p",
        "camera_ready": "Camera \u0111\u00e3 s\u1eb5n s\u00e0ng. Nh\u1ea5n Ch\u1ee5p \u0111\u1ec3 th\u00eam \u1ea3nh v\u00e0o cu\u1ed9c tr\u00f2 chuy\u1ec7n.",
        "camera_unavailable": "Kh\u00f4ng m\u1edf \u0111\u01b0\u1ee3c camera.",
        "camera_missing": "Ch\u01b0a c\u00e0i opencv-python.",
        "camera_save_dir": "\u1ea2nh ch\u1ee5p s\u1ebd \u0111\u01b0\u1ee3c l\u01b0u t\u1ea1i: {path}",
        "camera_save_failed": "Kh\u00f4ng l\u01b0u \u0111\u01b0\u1ee3c \u1ea3nh v\u1eeba ch\u1ee5p.",
        "system_reply_text": "T\u00f4i \u0111\u00e3 nh\u1eadn n\u1ed9i dung v\u00e0 s\u1ebd x\u1eed l\u00fd trong ng\u1eef c\u1ea3nh cu\u1ed9c tr\u00f2 chuy\u1ec7n n\u00e0y.",
        "system_reply_image": "\u0110\u00e3 nh\u1eadn \u1ea3nh. T\u00f4i s\u1ebd d\u00f9ng \u1ea3nh l\u00e0m d\u1eef li\u1ec7u \u0111\u1ea7u v\u00e0o cho cu\u1ed9c tr\u00f2 chuy\u1ec7n n\u00e0y.",
        "image_model_error": "B\u1ea3n d\u1ef1ng local n\u00e0y kh\u00f4ng c\u00f3 ph\u00e2n t\u00edch \u1ea3nh ngo\u1ea1i tuy\u1ebfn.",
        "system_unavailable": "B\u1ea3n d\u1ef1ng n\u00e0y ch\u1ea1y local ho\u00e0n to\u00e0n v\u00e0 kh\u00f4ng d\u00f9ng d\u1ecbch v\u1ee5 b\u00ean ngo\u00e0i.",
        "system_reply_camera": "\u0110\u00e3 nh\u1eadn \u1ea3nh ch\u1ee5p t\u1eeb camera v\u00e0 th\u00eam v\u00e0o cu\u1ed9c tr\u00f2 chuy\u1ec7n.",
        "empty_send": "H\u00e3y nh\u1eadp tin nh\u1eafn tr\u01b0\u1edbc khi g\u1eedi.",
        "info_title": "Th\u00f4ng tin",
        "loading_model": "\u0110ang kh\u1edfi \u0111\u1ed9ng x\u1eed l\u00fd gi\u1ecdng n\u00f3i c\u1ee5c b\u1ed9...",
        "recording_status": "\u0110ang l\u1eafng nghe...",
        "voice_error": "Kh\u00f4ng nh\u1eadn di\u1ec7n \u0111\u01b0\u1ee3c gi\u1ecdng n\u00f3i ho\u1eb7c l\u1ed7i mic.",
        "settings_title": "C\u00e0i \u0111\u1eb7t",
        "camera_window": "Ch\u1ee5p \u1ea3nh t\u1eeb camera",
        "attach_image_label": "\u1ea2nh \u0111\u00e3 ch\u1ecdn",
        "attach_text_label": "T\u1ec7p v\u0103n b\u1ea3n",
        "attach_camera_label": "\u1ea2nh ch\u1ee5p t\u1eeb camera",
        "mode_badge": "Ch\u1ebf \u0111\u1ed9",
        "today": "H\u00f4m nay",
        "yesterday": "H\u00f4m qua",
        "days_ago": "ng\u00e0y tr\u01b0\u1edbc",
        "english": "Ti\u1ebfng Anh",
        "vietnamese": "Ti\u1ebfng Vi\u1ec7t",
        "delete_chat": "X\u00f3a tr\u00f2 chuy\u1ec7n",
        "confirm_delete_title": "X\u00e1c nh\u1eadn x\u00f3a",
        "confirm_delete_msg": "B\u1ea1n c\u00f3 ch\u1eafc mu\u1ed1n x\u00f3a cu\u1ed9c tr\u00f2 chuy\u1ec7n n\u00e0y kh\u00f4ng?",
        "sidebar_expand": "M\u1edf r\u1ed9ng thanh b\u00ean",
        "sidebar_collapse": "Thu g\u1ecdn thanh b\u00ean",
        "medical_analyzing": "\u0110ang ph\u00e2n t\u00edch \u1ea3nh y khoa...",
        "medical_pending": "\u0110ang ch\u1ea1y pipeline s\u00e0ng l\u1ecdc y d\u01b0\u1ee3c...",
    },
}


def translate(language: str, key: str) -> str:
    return TRANSLATIONS.get(language, TRANSLATIONS["en"]).get(key, TRANSLATIONS["en"].get(key, key))
